# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quote-api-ingress
  namespace: hotel-quotes
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: quotes.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quote-api
            port:
              number: 80
